version: "3.8"
services:
  db:
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: replace_with_user
      POSTGRES_PASSWORD: replace_with_pass

volumes:
  postgres-data: null
